### ISSUE TITLE
STAIN_NORM_TARGET_IMAGE = './data/target.png'

### ISSUE THREAD

**Issue by wwrong01** [wang-kang-6/CGT#1]
i don't known what this is  refer to,please tell me,thx a lot!

**Comment by wang-kang-6** [comment]
The target image is used for normalization. It is updated in the latest commit.

**Comment by wwrong01** [comment]
my dear teacher,
&nbsp; &nbsp; &nbsp;thanks for your response for my first question.wish you good ! Looking forward to your reply for the second issue!&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;your sincere reader




王伟蓉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-kang-6/CGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-kang-6/CGT] STAIN_NORM_TARGET_IMAGE = './data/target.png' (Issue #1)





 
The target image is used for normalization. It is updated in the latest commit.
