### ISSUE TITLE
w = torch.load(w_name)

### ISSUE THREAD

**Issue by wwrong01** [wang-kang-6/CGT#2]
Hi:
   1. There have  the code "w = torch.load(w_name)" in dataloader.py  , you use "torch.load" means "w_name" has already created and saved before ,so how do you created this before? 
   2. is there a single .py file to generate or i just need to copy a new "weights" file and change the file extension from".bin" to ".pt"?
   3. I have tried the later and have error "_pickle.UnpicklingError: invalid load key, '?'."
   Can you please  clarify my doubt? I will very appreciate your help，thx！

**Comment by wang-kang-6** [comment]
These files are used to measure the distance between the graph nodes. I am uploading a complete dataset. Please be patient while waiting.

**Comment by wang-kang-6** [comment]
Please download all files by https://drive.google.com/file/d/18GV32dbaMiCdfXaUcElOH025w_5tWdvD/view?usp=drive_link. Then you need to split them into training and testing datasets.

**Comment by wwrong01** [comment]
Hi teacher，
&nbsp; &nbsp; &nbsp; That helps me! Thx a lot ,wish you good every day, and i will take further concern about ur works.😇😇😇





---Original---
From: "Kang ***@***.***&gt;
Date: Thu, Apr 25, 2024 20:56 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wang-kang-6/CGT] w = torch.load(w_name) (Issue #2)




 
Please download all files by https://drive.google.com/file/d/18GV32dbaMiCdfXaUcElOH025w_5tWdvD/view?usp=drive_link. Then you need to split them into training and testing datasets.

**Comment by wwrong01** [comment]
Hi teacher,
&nbsp; &nbsp; &nbsp; I have trained the model once according to the data you provided&nbsp; ,and i got the results like:

Comparing your results in the paper, I think there might be something I missed. Could you give me some hints?Or maybe my environment&nbsp;torch version (1.12.1+cu113)&nbsp;&nbsp;configuration affect the results?
&nbsp; &nbsp; &nbsp;&nbsp;

&nbsp; &nbsp; &nbsp; Thank you for taking the time to respond to my multiple inquiries.wish you have good time!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;your sincere reader


王伟蓉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wang-kang-6/CGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-kang-6/CGT] w = torch.load(w_name) (Issue #2)





 
These files are used to measure the distance between the graph nodes. I am uploading a complete dataset. Please be patient while waiting.

**Comment by wwrong01** [comment]
Sorry teacher, forget about this. I apologize for the disturbance. I haven’t run the reference.


王伟蓉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "王龙龙"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月27日(星期六) 中午1:54
***@***.***&gt;;

主题:&nbsp;回复： [wang-kang-6/CGT] w = torch.load(w_name) (Issue #2)



Hi teacher,
&nbsp; &nbsp; &nbsp; I have trained the model once according to the data you provided&nbsp; ,and i got the results like:

Comparing your results in the paper, I think there might be something I missed. Could you give me some hints?Or maybe my environment torch version (1.12.1+cu113) &nbsp;configuration affect the results?
&nbsp; &nbsp; &nbsp; 

&nbsp; &nbsp; &nbsp; Thank you for taking the time to respond to my multiple inquiries.wish you have good time!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;your sincere reader


王伟蓉
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "wang-kang-6/CGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-kang-6/CGT] w = torch.load(w_name) (Issue #2)





 
These files are used to measure the distance between the graph nodes. I am uploading a complete dataset. Please be patient while waiting.

**Comment by wwrong01** [comment]
Dear reacher Wang,
&nbsp; &nbsp; &nbsp;Happy May Day!&nbsp;&nbsp;In the previous email, I mentioned the issue with the experiments not yielding satisfactory results. After conducting several more experiments, I still have not achieved the outcomes depicted in the article. I kindly request your insights once again!&nbsp;Wish you have happy holiday!




王伟蓉
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "王龙龙"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月27日(星期六) 中午1:54
***@***.***&gt;;

主题:&nbsp;回复： [wang-kang-6/CGT] w = torch.load(w_name) (Issue #2)



Hi teacher,
&nbsp; &nbsp; &nbsp; I have trained the model once according to the data you provided&nbsp; ,and i got the results like:

Comparing your results in the paper, I think there might be something I missed. Could you give me some hints?Or maybe my environment torch version (1.12.1+cu113) &nbsp;configuration affect the results?
&nbsp; &nbsp; &nbsp; 

&nbsp; &nbsp; &nbsp; Thank you for taking the time to respond to my multiple inquiries.wish you have good time!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;your sincere reader


王伟蓉
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "wang-kang-6/CGT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月24日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wang-kang-6/CGT] w = torch.load(w_name) (Issue #2)





 
These files are used to measure the distance between the graph nodes. I am uploading a complete dataset. Please be patient while waiting.

**Comment by wu-bytecat** [comment]
> Please download all files by https://drive.google.com/file/d/18GV32dbaMiCdfXaUcElOH025w_5tWdvD/view?usp=drive_link. Then you need to split them into training and testing datasets.



Hello teacher, the link address of the dataset cloud drive shows that there is no permission to access and download. Could you please grant the download permission? Thank you very much

**Comment by wu-bytecat** [comment]
> Hi teacher， &nbsp; &nbsp; &nbsp; That helps me! Thx a lot ,wish you good every day, and i will take further concern about ur works.😇😇😇
> […](#)
> ---Original--- From: "Kang ***@***.***&gt; Date: Thu, Apr 25, 2024 20:56 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [wang-kang-6/CGT] w = torch.load(w_name) (Issue #2) Please download all files by https://drive.google.com/file/d/18GV32dbaMiCdfXaUcElOH025w_5tWdvD/view?usp=drive_link. Then you need to split them into training and testing datasets. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Hello, the link address provided by the teacher shows that there is no permission to access and download. Have you downloaded the file before? Could you please send me a copy? Thank you very much

**Comment by wu-bytecat** [comment]
> [wwrong01](/wwrong01)

Have you resolved this issue yet? If so, could you please guide me? Thank you
